from collections import namedtuple

# before you start: change filepath to archives location
filepath = '/Volumes/pool-duderstadt/Matthias/Manuscript/Archives_published/'

# do not change the code below
DataSet = namedtuple('DataSet', ['filepath', 'name', 'archive_type', 'accept_tag', 'labels'])

datasets = [DataSet(filepath=filepath,
                    name='Transcription_naked-DNA_ATP_LD555.yama', archive_type='DnaMoleculeArchive',
                    accept_tag='accept', labels=dict(T7='ybbR-LD555')),
            DataSet(filepath=filepath,
                    name='Transcription_naked-DNA_ATPgS_LD555.yama', archive_type='DnaMoleculeArchive',
                    accept_tag='accept', labels=dict(T7='ybbR-LD555')),
            DataSet(filepath=filepath,
                    name='Photobleaching_licensed-DNA_ATP.yama', archive_type='DnaMoleculeArchive',
                    accept_tag='accept', labels=dict(ORC='SORT-LD555', MCM='ybbR-LD655')),
            DataSet(filepath=filepath,
                    name='Photobleaching_licensed-DNA_ATPgS.yama', archive_type='DnaMoleculeArchive',
                    accept_tag='accept', labels=dict(ORC='SORT-LD555', MCM='ybbR-LD655')),
            DataSet(filepath=filepath,
                    name='Photobleaching_stalled_RNAP.yama', archive_type='DnaMoleculeArchive',
                    accept_tag='accept', labels=dict(T7='ybbR-LD655')),
            DataSet(filepath=filepath,
                    name='Transcription_ORC-DNA_ATP.yama', archive_type='DnaMoleculeArchive',
                    accept_tag='accept', labels=dict(ORC='SORT-LD555', T7='ybbR-LD655')),
            DataSet(filepath=filepath,
                    name='Transcription_ORC-DNA_ATP_stuck-ORC.yama', archive_type='SingleMoleculeArchive',
                    accept_tag='accept', labels=dict(ORC='SORT-LD555')),
            DataSet(filepath=filepath,
                    name='Transcription_naked-DNA_ATP_LD655.yama', archive_type='DnaMoleculeArchive',
                    accept_tag='accept', labels=dict(T7='ybbR-LD655')),
            DataSet(filepath=filepath,
                    name='Transcription_naked-DNA_ATP_AF488.yama', archive_type='DnaMoleculeArchive',
                    accept_tag='accept', labels=dict(T7='SNAP-AF488')),
            DataSet(filepath=filepath,
                    name='Transcription_naked-DNA_T7T_ATP.yama', archive_type='DnaMoleculeArchive',
                    accept_tag='accept', labels=dict(T7='ybbR-LD655')),
            DataSet(filepath=filepath,
                    name='Transcription_ORC-DNA_T7T_ATP.yama', archive_type='DnaMoleculeArchive',
                    accept_tag='accept', labels=dict(ORC='SORT-LD555', T7='ybbR-LD655')),
            DataSet(filepath=filepath,
                    name='Transcription_ORC-DNA_T7T_ATP_stuck-ORC.yama', archive_type='SingleMoleculeArchive',
                    accept_tag='accept', labels=dict(ORC='SORT-LD555')),
            DataSet(filepath=filepath,
                    name='Transcription_licensed-DNA_T7T_ATPgS.yama', archive_type='DnaMoleculeArchive',
                    accept_tag='accept', labels=dict(T7='SNAP-AF488', ORC='SORT-LD555', MCM='ybbR-LD655')),
            DataSet(filepath=filepath,
                    name='Transcription_licensed-DNA_T7T_ATP.yama', archive_type='DnaMoleculeArchive',
                    accept_tag='accept', labels=dict(T7='SNAP-AF488', ORC='SORT-LD555', MCM='ybbR-LD655')),
            DataSet(filepath=filepath,
                    name='Transcription_licensed-DNA_ATP_LS.yama', archive_type='DnaMoleculeArchive',
                    accept_tag='accept', labels=dict(T7='ybbR-LD555', MCM='ybbR-LD655')),
            DataSet(filepath=filepath,
                    name='Transcription_licensed-DNA_ATP_HS.yama', archive_type='DnaMoleculeArchive',
                    accept_tag='accept', labels=dict(T7='ybbR-LD555', MCM='ybbR-LD655')),
            DataSet(filepath=filepath,
                    name='Transcription_overlicensed-DNA_ATP_LS.yama', archive_type='DnaMoleculeArchive',
                    accept_tag='accept', labels=dict(T7='ybbR-LD555', MCM='ybbR-LD655')),
            DataSet(filepath=filepath,
                    name='Transcription_licensed-DNA_ATPgS_LS.yama', archive_type='DnaMoleculeArchive',
                    accept_tag='accept', labels=dict(T7='ybbR-LD555', MCM='ybbR-LD655')),
            DataSet(filepath=filepath,
                    name='Transcription_licensed-DNA_ATPgS_HS.yama', archive_type='DnaMoleculeArchive',
                    accept_tag='accept', labels=dict(T7='ybbR-LD555', MCM='ybbR-LD655')),
            DataSet(filepath=filepath,
                    name='Transcription_overlicensed-DNA_ATP_HS.yama', archive_type='DnaMoleculeArchive',
                    accept_tag='accept', labels=dict(T7='ybbR-LD555', MCM='ybbR-LD655')),
            DataSet(filepath=filepath,
                    name='Transcription_high-chromatin-DNA.yama', archive_type='DnaMoleculeArchive',
                    accept_tag='accept', labels=dict(NUC='LD555-H3', T7='ybbR-LD655')),
            DataSet(filepath=filepath,
                    name='Transcription_low-chromatin-DNA.yama', archive_type='DnaMoleculeArchive',
                    accept_tag='accept', labels=dict(NUC='LD555-H3', T7='ybbR-LD655')),
            DataSet(filepath=filepath,
                    name='Photobleaching_low-chromatin-DNA.yama', archive_type='DnaMoleculeArchive',
                    accept_tag='accept', labels=dict(NUC='LD555-H3')),
            DataSet(filepath=filepath,
                    name='Transcription_low-chromatin-licensed-DNA_ATP_1.yama', archive_type='DnaMoleculeArchive',
                    accept_tag='accept', labels=dict(T7='SNAP-AF488', NUC='LD555-H3', MCM='ybbR-LD655')),
            DataSet(filepath=filepath,
                    name='Transcription_low-chromatin-licensed-DNA_ATPgS.yama', archive_type='DnaMoleculeArchive',
                    accept_tag='accept', labels=dict(T7='SNAP-AF488', NUC='LD555-H3', MCM='ybbR-LD655')),
            DataSet(filepath=filepath,
                    name='Transcription_high-chromatin-licensed-DNA_ATP.yama', archive_type='DnaMoleculeArchive',
                    accept_tag='accept', labels=dict(T7='SNAP-AF488', NUC='LD555-H3', MCM='ybbR-LD655')),
            DataSet(filepath=filepath,
                    name='Transcription_low-chromatin-licensed-DNA_ATP_2.yama', archive_type='DnaMoleculeArchive',
                    accept_tag='accept', labels=dict(T7='SNAP-AF488', NUC='LD555-H3', MCM='ybbR-LD655')),
            DataSet(filepath=filepath,
                    name='MCM_high-salt_diffusion.yama', archive_type='DnaMoleculeArchive',
                    accept_tag='accept', labels=dict(MCM='ybbR-LD655'))]
